apiVersion: apps/v1

kind: Deployment

metadata:

  name: mariadb-deployment

  namespace: wp

spec:

  replicas: 1

  selector:

    matchLabels:

      app: mariadb

  template:

    metadata:

      labels:

        app: mariadb

    spec:

      containers:

      - name: mariadb

        image: mariadb:10.6.4-focal

        # command:

        #  - "--default-authentication-plugin=mysql_native_password"

        env:

          - name: MYSQL_ROOT_PASSWORD

            value: somewordpress

          - name: MYSQL_DATABASE

            value: wordpress

          - name: MYSQL_USER

            value: wordpress

          - name: MYSQL_PASSWORD

            value: wordpress

        ports:

          - containerPort: 3306

---

apiVersion: v1

kind: Service

metadata:

  name: mariadb-service

  namespace: wp

spec:

  selector:

    app: mariadb

  ports:

    - protocol: TCP

      port: 3306

      targetPort: 3306

