apiVersion: apps/v1

kind: Deployment

metadata:

  name: wordpress-deployment

  namespace: wp

spec:

  replicas: 1

  selector:

    matchLabels:

      app: wordpress

  template:

    metadata:

      labels:

        app: wordpress

    spec:

      containers:

      - name: wordpress

        image: wordpress:latest

        env:

          - name: WORDPRESS_DB_HOST

            value: mariadb-service

          - name: WORDPRESS_DB_USER

            value: wordpress

          - name: WORDPRESS_DB_PASSWORD

            value: wordpress

          - name: WORDPRESS_DB_NAME

            value: wordpress

        ports:

          - containerPort: 80

---

apiVersion: v1

kind: Service

metadata:

  name: wordpress-service

  namespace: wp

spec:

  selector:

    app: wordpress

  ports:

    - protocol: TCP

      port: 80

      targetPort: 80

---

apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:

  name: wordpress-ingress

  namespace: wp

spec:

  rules:

  - host: wp.kube

    http:

      paths:

      - path: /

        pathType: Prefix

        backend:

          service:

            name: wordpress-service

            port:

              number: 80

---

apiVersion: autoscaling/v2

kind: HorizontalPodAutoscaler

metadata:

  name: wordpress-hpa

  namespace: wp

spec:

  scaleTargetRef:

    apiVersion: apps/v1

    kind: Deployment

    name: wordpress-deployment

  minReplicas: 1

  maxReplicas: 5

  metrics:

  - type: Resource

    resource:

      name: cpu

      target:

        type: Utilization

        averageValue: 10m

